### ISSUE TITLE
2021.12.10 (금) _ 휴회기간 과제 준비

### ISSUE THREAD

**Issue by brainini** [XREAL-SNU/xTown#11]
## 현재 상황
- 휴회기간 : 12/6~1/2 -> 1월 3일에 휴회 후 첫 세션
- 기말고사 마무리 되는 시점인 12/20에 과제 공지 예정
- 팀별 멀티플레이어 게임 미니 프로젝트 진행 제안함 (by 태구)
- 12/20에 메인 프로젝트 팀빌딩도 동시 진행 예정.

## 논의 사항
- 메인 프로젝트 팀빌딩한 팀으로 휴회 기간 팀 과제 줄지?
- 과제 보충 및 제안 요청
    - [과제 링크 1](https://www.youtube.com/watch?v=mPCNTi3Booo&list=PL3KKSXoBRRW3YE4UMnRH762vOhSHLdnpK)
    - [과제 링크 2](https://www.youtube.com/watch?v=zPZK7C5_BQo&list=PLhsVv9Uw1WzjI8fEBjBQpTyXNZ6Yp1ZLw&index=1)

## 해야 할 일
- 논의 후 결정

**Comment by brainini** [comment]
다빈님 : 디자인팀은 휴회기간 중으로 XTown 기획을 작성할 예정이기 때문에 팀이 빨리 꾸며질수록 좋은 상황이다.
->오늘중으로 슬랙 프로젝트공지방에 디자인팀 모집 공지 올릴 것.

한준님 : 메인프로젝트 팀빌딩 대로 과제 나가자. 


- **UI팀 분리 의견** : 프론트엔드 개발 과정이 들어가기 때문에 워크로드가 상당할 예정. 디자인팀과 개발팀 모두가 필요할 것 같음. 그래서 UI팀을 따로 분리하는 것이 필요한 상황 -> 만약 하게 되면 진님께서 맡아서 진행해주시면 좋을 듯.
    - 슬랙에 의견 공지. 
 
첫번째 논의 사항은 메인프로젝트 팀빌딩으로 가는 것으로 의결.

각 팀별로 과제 의견 이 이슈에 코멘트 달기.(~12/15)

**Comment by Hyewon0309** [comment]
Youtube에서 Unity3d를 이용해 마인크래프트를 구현해보는 tutorial이 있어 가져왔습니다.
실제로 아는 게임을 직접 구현해 보는 것이 더 재밌을 것 같고, 구현하는 과정에서 3d object, texture, UI 등에 대해 세세하게 배울 수 있을 것 같아서 제안합니다. 시간은 많이 걸릴 것 같은데 한 번에 끝까지 구현하는 것이 아니라 특정 부분까지 구현하는 것을 목표로 하면 괜찮을 것 같습니다!

[과제 참고 링크](https://www.youtube.com/watch?v=h66IN1Pndd0&list=PLVsTSlfj0qsWEJ-5eMtXsYp03Y9yF1dEn)

**Comment by JasonK2K** [comment]
photon 사용하여 멀티플레이어 fps 구현하는 예제입니다.

**Comment by JasonK2K** [comment]
photon, fps 라이브러리 사용하여 fps 멀티 플레이어 게임 만드는 예제입니다. 
나온지 조금 된 예제이긴 한데, fps 장르가 3D 게임을 선도하듯이 한번 그 원리를 알아보면 좋을 것 같다는 생각이 드네요. 
최신 버전으로 라이브러리 업데이트해서 하면 괜찮을 것 같습니다. 만약 이걸로 한다면 
버전 차이로 인해 버그 발생하는 부분이 있나 확인해봐야겠네요.
[과제 유튜브 링크](https://www.youtube.com/watch?v=8fg5vtwBll8&list=PLu2K_XrV43vBp40aez8XAjPt-MmzLdJnG&index=17)

**Comment by Aimee0122** [comment]
기본적인 부분부터 확실히 연습해보면 좋을 것 같아서 완전한 게임이나 프로그램 구현보다는 캐릭터 에셋 애니메이션 연습 과제를 준비해보았습니다. 튜토리얼을 단순히 따라하기보다는 가능하면 자신이 원하는 에셋으로 추가적인 애니메이션 기능을 넣어서 제출하면 좋을 것 같습니다.

[과제링크 1](https://www.youtube.com/watch?v=qc0xU2Ph86Q)
[과제링크 2](https://www.youtube.com/watch?v=ReauId6jFFI)

**Comment by ahnjinmo** [comment]
xtown 내에 들어갈 게임을 만들기 전에, 너무 볼륨이 크지 않으면서 흥미를 느낄 만한 미니게임 혹은 다른 게임에서 나오는 독특한 feature를 클론해보면 좋을 것 같아서 관련 영상들을 찾아봤습니다. 주로 [MixandJam](https://www.youtube.com/c/MixandJam/videos) 이라는 채널에 이런 영상들이 많이 있는데, 그 중 아래 세 가지 정도의 수준이면 해볼만 할 것 같습니다. 그리고 한 개 만으로는 로드가 적다면 여러 개를 해도 좋을 것 같습니다. 그리고 맵/캐릭터/애니메이션 에셋 등을 임포트하고 적용하는 과정이나 쉐이더 등등에 대한 세부적인 내용은 생략되어 있지만, 이런 부가적인 부분들은 직접 찾아보면서 만들게 해도 좋을 것 같습니다.

1. [Tilt Quest 미니게임](https://www.youtube.com/watch?v=JewxuKNLF2c)
2. [마리오파티 - Slaparazzi 미니게임](https://www.youtube.com/watch?v=d5fItlYCzgE)
3. [마리오파티 - 캐릭터 발사](https://www.youtube.com/watch?v=T_3cne2tzYM)

etc. [폴가이즈](https://youtube.com/playlist?list=PLD4OdGjxbaBzZLT6872LDrK2Jvm50TMiz)

**Comment by jinny1t** [comment]
아직 UI팀을 모집하지 않아서 디자인 팀에서 우선적으로 모집해보고 인원이 충분하지 못하다고 판단되면  UI쪽의 경험이 있거나 관심이 있는 학회분들이 있을 수 있어서 학회 전체에도 공지를 띄어볼 예정입니다. 21일까지 모집을 완료하고(제가 시험이 21일날 끝나서ㅠㅠ) 22일부터 빠르게 팀원들과 함께 UX적인 측면에서 Xtown의 User flow와  IA를 기획하고 그걸 구현하는 UI를 디자인하기 전에  디자인적으로  참고할 수 있는 webgl 사이트들을 리서치 할 계획입니다. (예시 레퍼런스 : https://www.blueyard.com/ , https://gallery.swell.ripple.com/room/gonzalo-miranda) 이 후 UI 와이어프레임을 휴회기간이 끝나기 전까지 만들어보는것을 목표로 하겠습니다.

**Comment by AliceOfSNU** [comment]
약간 너무 본격적일수도 있는데
투토리얼 따라하는게 아니라 부딪히면서 배우는 단계로
나아가야 하지 않을까 싶어서..
시의적절하게 크리스마스 트리 만들면 어떨까 싶습니다

대강 기획 pdf 로 첨부합니다
[christmas-tree.pdf](https://github.com/XREAL-SNU/xTown/files/7721139/christmas-tree.pdf)

아직 정리가 안됐는데 정리해서 requirement 잘 써서 과제로 내면 어떨까 싶습니다.

**Comment by Abecid** [comment]
Unity Learn이 Unity를 배우는데 기본이자 정석인것 같은데 여기서 Pathway가 크게 세 가지가 있는 것 같아요 (Essentials, Junior Programming, Creative Core)

이 중 Essentials만 과제로 나간 것으로 알고있는데 세가지를 간단히 정리하자면
1. [Essentials](https://learn.unity.com/pathway/unity-essentials) (2 주)
  유니티 첫 입문자 위한 수업
  
  미션1: Get started with Unity
    - 유니티 프로젝트 시작 및 관리: Unity Editor 다운받고 Unity Hub로 관리
    - Unity Editor Essentials: scene 시작 및 관리, Scene view에서 3D랑 2D 공간 이동하기
  미션2: Explore Unity
    - Real-time Industry Essentials: 간단한 유니티 역사와 실시간 creation 산업에 대해 알기, 실시간 production cycle 배우기
    - Scene Building Essentials: 기본 element, GameObject 만들고 바꾸기, Component와 스크립트 활용해보기, GameObject의 겉모습 바꾸기, GameObject의 기본 물리 시스템 구현하기
    - Publishing: 기본 빌드를 만들고 공유해보기
  미션3: Learn Unity
    - 직장 위한 커리어 준비 


2. [Junior Programming](https://learn.unity.com/pathway/junior-programmer) (12 주)
  코딩 기반 수업. 유니티로 주니어 개발자로 취업하고 싶을 때 좋은 수업.

  미션1
    - Code Comprehension: 코드 이해하고 개선하기
    - Application Scripting: Unity의 다양한 API 활용해보기, 다양한 Data Type 만들어보기
  미션2
    - Debegging: Compile이 안되는 코드 고치기
  미션3
    - Version Control: Version Control로 프로젝트 개발하고 Best Practice 배우기
    - Application Scripting (심화): Application State에서 Scene Flow 만들기, 유저 세션과 scene간에 data persistence 구현하기
  미션4
    - Code Optimization: 코드 효율성 높이고 best practice 배우기, debug 퍼포먼스 개선하기
    - Programming Theory: 객체지향 프로그래밍 이론 및 구현
  

3. [Creative Core](https://learn.unity.com/pathway/creative-core) (10주) 
  Unity 크리에이터가 되기 위한 수업. 프리랜서로 직장 구하고 싶을 때 좋은 수업.
  (VFX, Lighting, Animation, Audio, UI and other creative skills, no programming required)

  미션1: Intro
    - Design Process
    - Project Management
    - Render Pipeline
    - Beginner Research
  미션2: Shaders and Materials
  미션3: Lighting
  미션4: Animation
    - Unity기반 3D 애니메이션
    - Imported 3D 애니메이션
  미션5: VFX (Visual Effects)
  미션6: Cameras
  미션7: Post-processing
  미션8: Audio
  미션9: UI
  미션10: Prototyping



이 것을 참조하고 개개인의 능력, 성향, 관심분야에 맞게 Pathway와 미션 기준으로 과제를 주면 좋을 것 같습니다. (과제는 일주일에 미션 2개 분량을 추천합니다)
