### ISSUE TITLE
2021.12.10 (금) _ chat ui 디스플레이 안되는 bug

### ISSUE THREAD

**Issue by AliceOfSNU** [XREAL-SNU/xTown#15]
PhotonChat: #10 

[issue]
화면 비율이 바뀌었을 때 **chat ui가 제대로 표시되지 않고 빨간 x로 표시**되는 문제가 있습니다.

[potential causes]
어떨 때 발생한 다 외에 아직 원인은 찾지 못했으나 anchor와 offset으로 정의된 ui element들이 화면 비율이 바뀌면
parent canvas 영역에서 벗어나 디스플레이 되지 않는 것 같습니다.

[how to reproduce]
게임 플레이 버튼 클릭 후 게임 window 비율 변경 -> inspector view로 돌아가보면 ui element들이 빨간 x로 바뀐 것 확인가능

[comments]
UI 팀에서 검토 부탁드립니다.

**Comment by brainini** [comment]
글로만 써져있어 직관적이지 않고 전 해당 사항을 제 local에서 확인하지 못해서 사진 첨부해주시면 좋을 것 같습니다.

**Comment by AliceOfSNU** [comment]
재현이 안되서 일단 close합니다
