### ISSUE TITLE
표준화작업_ 디렉토리 정리

### ISSUE THREAD

**Issue by AliceOfSNU** [XREAL-SNU/xTown#22]
목표:
프로젝트 directory를 어떻게 정리하고 관리할지 논의

1. 외부 에셋을 어느 폴더에 관리할지
2. Scene마다 폴더를 따로 둘지, 둔다면 각 scene의 폴더 구조는 어떻게 되어야 하는지
3. 기능단위로 폴더를 따로 둘지, 둔다면 각 기능의 폴더 구조는 어떻게 되어야 하는지

를 논의해 보았으면 좋겠습니다.

**Comment by AliceOfSNU** [comment]
일단 제 생각은 Scene별로 폴더를 둘지는 조금 더 후에 여러 scene들이 만들어지면 생각해 보더라도,
top level (project root 또는 scene root) 밑 구조는 대략 다음과 같이 가져가면 어떨까 합니다

![image](https://user-images.githubusercontent.com/86138312/146713382-c663a6fd-7894-47a6-b6a5-9069937ad046.png)

- Scripts: all .cs files -> 기능별로 분리
    ㄴ Chat@Server
    ㄴ VoiceChat@Server
    ㄴ AvatarControl@Avatar
    @뒤는 namespace와 일치 com.XReal.Xtown.Server
    
- StaticAssets: 해당 scene에서 사용하는(혹은 프로젝트 전체에서 사용하는) 정적 asset
 : BGM, videos, images, 등 package manager로 import 해온 것 뿐 아니라 직접 업로드한 모든 정적 asset 포함
  -> 다운받은 각 asset 마다 폴더를 따로 둠(예: StarterAssets, readyPlayerMe, FREEPetalsParticles V1 등) 
       vs 게임 내 오브젝트들의 분류 (예컨대 enviroment, characters, items, effects 등) 에 따라
  -> 각 asset의 root 밑에 서브디렉토리는 
   ㄴ Prefabs, 
   ㄴ Models(Mesh), 
   ㄴ Materials(material)
   ㄴ Textures(texture image files, normal maps etc) 
   ㄴ Scenes(에셋 다운로드하면 주는 예제 씬), 
   ㄴ Animations(Animations and animators) 
       + 그 외 폴더들 필요한대로(예: Physics, Audio, Inputs, FBX, shaders)

- Shaders
    ㄴ 아직 shader 코드가 없어서 나중에 생각

- Prefabs
    해당 scene에서 사용되는 prefabs들 -> 여기 폴더 구조는 암묵적인 rule이 생기면 거기에 따르면 충분할 거 같음
    예시)
    ㄴ Environment
    ㄴ Player
    ㄴ Items

**Comment by AliceOfSNU** [comment]
모든 폴더이름은 대문자 시작 camelcase 였으면 좋겠습니다

**Comment by brainini** [comment]
한준님 의견을 기본적인 unity의 폴더 구조를 이요하며 다음과 같이 정리하는 건 어떨까요?

Assets
 - Scenes
 - Scripts
 - Prefabs
 - StaticAssets
 - Shaders

다음과 같이 정리하고, Scenes를 제외한 각 폴더에서 하위 폴더를 각 Scene 이름대로 만들어서 관리하는 것이 좋아보입니다.

Scene별로 폴더를 만드는 것도 좋지만 이후 Scene간의 관계나 위계질서가 생길걸 감안하면 위의 방안처럼 병렬적으로 관리하는 게 좋아보입니다.

**Comment by AliceOfSNU** [comment]
태구님 의견 좋은 것 같아요. 근데 내가 A라는 scene에서 작업하고 있는데 script짜다가 prefab이 필요하면 상위폴더에서 다시 내 scene을 찾아야 하니까 이동거리가 길어지는것 같은데 장단점이 있는거 같습니다. 생각해보니까 여러 씬에 공통적으로 들어가는 파일들이 많을거 같아서 이런 경우엔 기능 단위로 폴더 이름을 파야 될지, 아니면 그냥 common 하위 폴더에 둘지..

**Comment by AliceOfSNU** [comment]
저번에 namespace 관련 얘기가 나왔었는데
<img width="705" alt="1640228991758" src="https://user-images.githubusercontent.com/86138312/147182274-1ebdf14a-9400-41f7-892c-33061a81169a.png">
요거 서버팀 과제 튜토리얼에 나온것 보고 말씀하신거 같은데
저도 GameManager, Controller 같은건 충분히 충돌 날 가능성이 있으니 필요하다고 생각합니다.

이름은

XReal.XTown.PhotonServer
XReal.XTown.Avatar
XReal.XTown.ScreenShare
이런식으로 가면 될것 같은데 이름을 어느 단위로 짓는게 좋을지,
그니까 chat 과 voicechat과 videochat이 같은 클래스들을 사용한다면
XReal.XTown.Chat.Common
XReal.XTown.Chat.VideoChat
이런식으로 hierarachical 하게 가는게 실무에서 보통 저렇게 하는지.. 저도 네임스페이스는 잘 안써봐서.. 알아봐야 할 것 같아요
