### ISSUE TITLE
클라이언트_캐릭터 선택 UI 생성

### ISSUE THREAD

**Issue by Hyewon0309** [XREAL-SNU/xTown#25]
## 목적
> 커스터마이징된 4개의 아바타 중 하나를 선택해 접속할 수 있도록 하는 UI 생성 및 각 아바타의 컨트롤러 구현
## 작업 상세 내용
- 4개의 아바타 중 하나를 선택하는 UI를 가지는 Scene 생성
## 참고 사항
- https://www.youtube.com/watch?v=3qlRgICRoeA&t=35s

**Comment by brainini** [comment]
- "클릭 안한 상태로 드래그 해도 카메라 각도가 계속 바뀌는데 클릭한 후에 드래그 하는거 혹은 alt누른채로 드래그 하는걸로 바꿈"
- "카메라 줌인, 줌아웃 (+/- 키 바인딩?)"
현재 playground scene에서만 avatar작동이 확인되는데 다빈님이 만들어놓은 mainroom이 적용되어 있는 mainroom scene에 해당 avatar를 올리고 건축물과 collider가 정상적으로 상호작용하는지 확인할 필요가 있을 것 같습니다.

제가 이전 풀리퀘에서 언급했던 위의 사항들도 추가적으로 구현이 필요해보입니다.
+ 더불어 지금 아바타의 경우 앉기버튼을 눌렀을 때 애니메이션이 자연스럽지 않습니다. 해당 사항도 추가 필요해보입니다.

**Comment by AliceOfSNU** [comment]
클릭후 드래그로 앵글 조절 및 + - 로 거리 조절 제가 추가할게요..

**Comment by Hyewon0309** [comment]
현재 진행 상황 공유드립니다.

- CharacterSelect Scene 생성해 4개의 customized avatar 중 하나를 선택해서 시작하는 기능 추가
- MainRoom Scene에 선택한 avatar 불러오기
- Avatar Controller, 콜라이더 구현
- Cinemachine을 이용한 카메라 구현

Todo

- [x] 클릭 후 드래그로 앵글 조절
- [x] + - 로 줌 인, 줌 아웃 구현

- Avatar의 앉기 애니메이션의 경우, 의자에 앉는 모션으로 보이는데 현재 MainRoom Scene에는 의자가 없어서 일단은 제외하려고 하는데 의견 부탁드립니다.

**Comment by ahnjinmo** [comment]
어차피 아직은 베이스라인이 목적이니까, 보여주기 위한 용도로 MainRoom Scene에 간단하게 의자 오브젝트를 넣어도 크게 문제는 없을 것 같기는 합니다. 그리고 character-select 브랜치에서 앉기를 하면 아래 영상처럼 되던데 맞나요? 

https://user-images.githubusercontent.com/89832796/147808706-81a47edd-a8aa-49bc-8961-6c7681482e20.mp4

**Comment by Hyewon0309** [comment]
네 맞습니다. 그 모션이 말씀드린 의자에 앉는 모션인 것 같은데 의자를 추가해 한 번 확인해보겠습니다. 지금은 다른 앉기 애니메이션도 찾아보는 중입니다.

**Comment by ahnjinmo** [comment]
찾아보니까 mixamo 애니메이션 import할 때 setting에 문제가 있어서 저렇게 애니메이션이 이상하게 나온 거네요. 아래와 같이 먼저 sitting animation의 Import settings에서 Rig setting을 Humanoid로 바꾸고, Animation setting에서 Root Transform - Bake Into Pose를 모두 체크하면 영상처럼 정상적으로 작동합니다!
![humanoid](https://user-images.githubusercontent.com/89832796/147815470-0c509a86-1b56-4a83-ad70-08acff40afb2.png)
![fwef](https://user-images.githubusercontent.com/89832796/147815052-a18e32b0-9cc0-47d1-9866-762f5dc7794d.png)

https://user-images.githubusercontent.com/89832796/147815067-53b82f43-5c88-4da4-918f-3cf5719dcc4a.mp4

**Comment by brainini** [comment]
제가 로컬에서 merge 하여 #26-lobby branch에 push하여 풀리퀘 반영하였습니다 확인 부탁드립니다.

**Comment by Hyewon0309** [comment]
확인했습니다:) 앉기 모션 빼고는 다 잘 작동하네요
