### ISSUE TITLE
서버, 클라이언트 - #31 Yacht Dice 2Players

### ISSUE THREAD

**Issue by AliceOfSNU** [XREAL-SNU/xTown#38]
## 목적
> multiplayer 모드 추가
## 작업 상세 내용
- [x] 순서 주고받는 로직 (Turns manager)
- [x] 멀티 모드에서 score board 상대방 점수 추가 
- [x] 컵 동기화
- [x] 자기 순서에 맞게 control을 넘겨주는 로직
- [x] 주사위 동기화
- [ ]  주사위 던진 결과 정보 주고받는 인터페이스 구현
- [x]  Strategy 선택 결과 정보 주고받는 인터페이스 구현
- [x]  둘의 점수 비교, 승자 판별 로직 (진홍님께 부탁..)
- [ ]  플레이어 두명만 받도록 방 join 로직
- [x]  xTown 프로젝트에 붙이기

**Comment by AliceOfSNU** [comment]
![initPlan](https://user-images.githubusercontent.com/86138312/148241188-a53a0602-2224-4ffc-a45e-56e63fecc3c4.png)
저희가 게임의 어느 시점에 어떤 정보들을 남한테 pass 할 것이고, 
어떤 정보들은 local에서 처리할 것인지 정해야 합니다

- 굴려진 주사위 숫자들과 rollcount(?)
- 두개의 dice 목록 (if changed.) 순서도(?)
- 선택한 strategy
- turn (몇번째 턴인지, 누구 턴인지)

위 그림은 대강 그 흐름을 정리해 놨습니다.. 진짜 대강대강.

**Comment by AliceOfSNU** [comment]
클린한 진홍님 클라이언트 코드만 있는 버전으로 내일 오후중에 브랜치를 파겠습니다! 월요일날 봬요

**Comment by JasonK2K** [comment]
넵 ㅎㅎ

**Comment by AliceOfSNU** [comment]
https://github.com/AliceOfSNU/NetcodeYacht/tree/dev
작업내용
- [x] 상속 방식으로 코드 추가한다고 가정, 수정이 필요한 스크립트들 모두 subclass 만듬
- [x] 자기 턴이 아니면 기다리는 로직 추가
- [x] 턴을 주고 받는 로직 추가
- [x] 주사위 던진 정보 등을 주고 받을 수 있는 인터페이스는 추가했으나, 아직 게임에 integrate하진 않음
- [x] 네트워크 연결 없을 시 싱글플레이 로직을 사용하도록 코드 추가

**Comment by AliceOfSNU** [comment]
01월 18일 작업할 내용
- XTown에 지금 작업하는 내용 다 연결 (yacht게임 내 포톤 코드를 저희 xtown 포톤 코드로 바꿔치기)
- 주사위 동기화
- 주사위 던진 결과 정보 event로 주고받기.

**Comment by AliceOfSNU** [comment]
----------- Task board -----------
- [ ] 주사위 동기화
- [x] 주사위 던진 결과 정보 주고받는 인터페이스 구현
- [ ] Strategy 선택 결과 정보 주고받는 인터페이스 구현
- [ ] 둘의 점수 비교, 승자 판별 로직 (진홍님께 부탁..)
- [ ] 플레이어 두명만 받도록 방 join 로직
- [x] xTown 프로젝트에 붙이기

**Comment by AliceOfSNU** [comment]
- singleplay 방법 : portal 통해 접속하지 않고 바로 yacht scene에서 플레이 하면 single play mode.
![image](https://user-images.githubusercontent.com/86138312/149882533-8302d6b2-ecdf-42c4-8305-570363edc374.png)

- 기본적으로 포탈로 들어가면 멀티플레이임. 
(이걸 singleplay로 선택하는 옵션을 넣을 수 있겠는데 일단 멀티플레이 잘 돌아가면)

**Comment by AliceOfSNU** [comment]
일단 주사위는 잘 동기화 됩니다.
![image](https://user-images.githubusercontent.com/86138312/150070780-50c1f8bf-57ab-4229-bbdc-b79f84420920.png)
