### ISSUE TITLE
클라이언트(생산성 도구 팀)- 유니티 시계 구현

### ISSUE THREAD

**Issue by Aimee0122** [XREAL-SNU/xTown#45]
## 현재 상황
- [유니티 시계 베이스라인 제작 튜토리얼을 공유하였으며, 기본 베이스라인 구현과 함께 각자 원하는 추가 기능 (ex. 알람)을 더하여 과제 제출 예정 ]

## 해야 할 일
- [과제 수합 이후 각자 구현해온 기능에 대한 피드백 / 실행 시 오류 여부 확인  ]

## 참고자료
- [https://youtu.be/_jqWxUFbNrg]
- [https://youtu.be/pbTysQw-WNs]

**Comment by ahnjinmo** [comment]
## 구현하려는 기능
* 시계에 **알람**을 설정하고, 설정된 시간이 되면 특정한 이벤트가 발생하는 기능

## 레퍼런스
https://youtu.be/sGo3Vnvq43k
<details>
<summary>펼치기</summary>
<div markdown="1">     
  
1. 알람 아이콘 선택
<img src="https://user-images.githubusercontent.com/89832796/149056929-46b74088-885f-4262-bf47-01278fed1a9c.jpg" width="100">

2. 알람 설정 패널 팝업
<img src="https://user-images.githubusercontent.com/89832796/149056938-86d31f64-13b6-4e53-80a9-220d98fc5392.jpg" width="150">

3. 알람 추가 패널 팝업
<img src="https://user-images.githubusercontent.com/89832796/149056953-305346b1-573c-4fc7-ad3e-fa44c627acfd.jpg" width="300">

4. 설정된 알람 관리 가능
<img src="https://user-images.githubusercontent.com/89832796/149056958-9f1c9337-f732-42a0-a06b-6ba0409232af.jpg" width="200">
</div>
</details>

## 현재 구현된 기능
- [x] 우상단에 현재 시간 디지털시계로 디스플레이
- [x] 원하는 알람 1개의 시간 설정 가능
- [x] 설정된 알람 시간이 되면 콘솔로 알림

## 디벨롭 가능한 사항
- [ ] 알람 여러 개 설정 및 적용 가능하게 모듈화
- [ ] 알람 세부 설정 기능 (ex. ~초 전 알림 등)
- [ ] 알람 이벤트 커스텀 기능 (ex. 사운드, 경고창 등)

## 작업 리포지토리
https://github.com/ahnjinmo/Alarm

**Comment by MondaySHB** [comment]
다음 주 회의 전까지 가능하면 panel에 알람 시간 목록 listing 기능 추가

**Comment by Aimee0122** [comment]
<1차 디벨롭-버튼 추가>
- 화면 우측 상단 버튼 클릭 시 각각 기본 시계/ 스탑워치 / 타이머 나오도록 구현
- 각 화면에서 다시 로비로 돌아갈 수 있도록 Back button도 구현

**Comment by ahnjinmo** [comment]
## 1차 디벨롭 (1/12~1/19)
- [X] 알람 여러 개 추가 및 리스팅 기능 (추가만 가능하고 실제 알람 기능과 연동은 구현되지 않음)

## 아직 구현되지 않은 사항 (1/19~)
- [ ] 시간 설정 시 +, - 버튼 동작
- [ ] 설정된 알람들 수정하는 기능
- [ ] 추가한 알름들의 실제 알람 기능
- [ ] private/public 알람의 동작 차이

## 추가 디벨롭 가능사항 (1/19~)
- [ ] 오른쪽에 현재 설정된 알람 볼 수 있는 미니 윈도우 구현
- [ ] 알람 이벤트 세부 설정 기능
- [ ] 설정된 알람으로부터 ~초/~분 전 경고 기능
- [ ] 알람 설정 시 현재로부터 +5분으로 설정하는 버튼

**Comment by ahnjinmo** [comment]
## 2차 디벨롭 (1/19~1/26)
- [X] 설정한 알람과 실제 알람기능 연동
- [X] 설정한 알람 편집 및 삭제 기능 추가
- [X] 알람 시간 설정 시 +/- 버튼 기능 추가
- [X] 베이스라인 알람 스크립트 정리 및 삭제
- [X] 주석 추가

## 추가 디벨롭 가능사항 (1/26~)
- [ ] 오른쪽에 현재 설정된 알람 볼 수 있는 미니 윈도우/탭 구현
- [ ] 알람 소리 선택 기능
- [ ] 알람 지속 시간 설정 기능
- [ ] 설정된 알람으로부터 ~초/~분 전 경고 기능
- [ ] private/public 알람의 동작 차이 (public알람으로 설정하면 모든 사람에게 알람 적용)
- [ ] 설정된 알람을 3D 공간 상에 놓는 시각적인 오브젝트로 놓아서 볼 수 있는 기능
