### ISSUE TITLE
클라이언트(아바타) - 아바타 커스터마이징 기능 구현

### ISSUE THREAD

**Issue by tehokim** [XREAL-SNU/xTown#51]
## 목적
> 아바타 커스터마이징 기능구현
## 작업 상세 내용
- [x] 아바타 모습 확인 구역
- [x] 커스터마이징 설정 구역 & 버튼
- [x] 카메라 줌인 & 이동
- [x] 카메라 리셋 버튼 (+)
## 참고 사항
![image](https://user-images.githubusercontent.com/95514277/149621843-1a9d9f5f-ad76-4baa-90d1-1e50a5d2b7b6.png)
- 아바타 모습 확인 구역
   1) 롤플레잉 게임 카메라 컨트롤 (유니티 3D)/ 마우스로 카메라 움직이기, 시점 조작 in 3D RPG
URL: https://www.youtube.com/watch?v=m5Ul-W4Sxqo
- 커스터마이징 설정 구역 & 버튼
  1) Unity Game Creator - Create a Game 09: Character Customization
URL: https://www.youtube.com/watch?v=UPSLgCtjddE&t=2560s

**Comment by tehokim** [comment]
- [x] 뒤로가기 버튼
- [x] 컬러 초기화 버튼 (+)

**Comment by AliceOfSNU** [comment]
혹시 avatar의 customizable property를 저장할 때 쓰는 Data class (monobehaviour 상속x, gameObject에 component로 attach 되는게 아니라, 플레이어한테 예속되는 class로, 약간 static class로 해도 괜찮을것 같다는 생각)를 하나 파서 거기에
1) 헬멧, 수트, 글러브, 백팩 PROPERTY 저장
2) LocalPlayer property(c# property말하는 거임) 로 현재 플레이어 아바타 gameObject를 반환_
예컨대 클래서 이름이 PlayerAvatar 라고 하면, 플레이어 아바타 머리 위에 뭐를 띄우고 싶으면,
transform.position = PlayerAvatar.LocalPlayer.transform.position + offset; 이렇게 쉽게 코딩 가능하도록

이 때, helmet, suit, gloves, backpack등 각각의 요소는, 지금 아바타가 변경되거나, customizing 가능한 부분이 추가, 삭제되도 유연하게 대체될 수 있도록 모두 IAvatarCustomizable 인터페이스 또는 AvatarCustomizablePart base class 상속 하도록 묶으면 어떨까 생각. 그럼 아까 저 data class안에서 각 요소에 대한 다형성 사용 가능.
