### ISSUE TITLE
클라이언트(아바타) - 아바타 표정 구현

### ISSUE THREAD

**Issue by be9904** [XREAL-SNU/xTown#57]
## 목적
> 우주복 모델 헬멧 부분에 표정이 나오도록 구현
## 작업 상세 내용
- 표정별 texture baking
- 입력키(미정)에 따라 헬멧에 보이는 표정 변경
## 참고 사항
- 모델은 헬멧, 몸, 신발, 장갑과 가방(?)으로 나누어져 있습니다. 아래 사진처럼 표정을 표현하려면 모델을 직접 편집하여 texture를 생성하고, unity에서 이를 별도의 material로 묶어주면 구현이 가능할 것 같습니다.
![helmet_uv](https://user-images.githubusercontent.com/61895947/149647495-c914768d-6c95-4164-be58-676dc8b16230.PNG)
- 진홍님께서 만들어주신 자료 (https://www.notion.so/2021sprinter/7fbeebb0e35b4d138505541a4faa9cb5)

**Comment by Hyewon0309** [comment]
이 부분도 다른 브랜치에서 작업해 Merge하여 Close합니다.
