### ISSUE TITLE
클라이언트 (생산성 도구 팀)- 스티키노트 구현

### ISSUE THREAD

**Issue by Aimee0122** [XREAL-SNU/xTown#74]
## 현재 상황
- [ 시계 구현과 병행하여 스티키 노트 구현을 시작]
## 계획
- [스티키 노트 1차 베이스라인 구현 전, 각자가 생각하는 스티키노트의 형태와 구현 방식 기록 ]
- [1차 베이스라인 구현 후 회의를 통해 각 베이스라인 확인해보며 피드백 / 스티키노트 개발 방향 구체화 예정]

**Comment by MondaySHB** [comment]
https://assetstore.unity.com/packages/tools/gui/sticky-memos-177929?locale=ko-KR
무료 asset인데 영상을 보았고 괜찮은거 같아 import를 해서
사용자 판넬에 추가해볼까 합니다

**Comment by ahnjinmo** [comment]
## 목표
3D 공간에 놓고 크기, 위치, 각도, 내용 등을 편집할 수 있는 스티키노트

## 레퍼런스
* Spatial에 있는 스티키노트 기능
![001](https://user-images.githubusercontent.com/89832796/150292711-dab21fa7-6455-45bd-a08a-3c2958733d7b.jpg)

## 기능
* 공간 상에 새로운 스티키노트 생성 및 삭제
* 텍스트 편집
* 위치/크기/각도 수정 (해당 스티키노트에 UI요소 바인딩 되어서, UI로 조절)

## 구현에 도움될 만한 참고자료
* UI를 3D 공간 상에 놓는 방법
  * https://youtu.be/Zwgj3mwOVlg
  * https://youtu.be/GuWEXBeHEy8
* 오브젝트를 UI 상에서 드래그로 이동하는 방법
  * https://youtu.be/Ac_eaOvNa-w
  * https://youtu.be/0yHBDZHLRbQ
* 오브젝트를 슬라이더 UI를 이용해 회전하는 방법
  * https://youtu.be/bxheIjLAXLE
* 오브젝트에 UI 바인딩해서 따라다니게 하는 방법
  * https://youtu.be/kUbDucw3LCQ

**Comment by AliceOfSNU** [comment]
https://youtu.be/HWgCAgKZpI8
이게 진짜 webGL 빌드에서도 돌아가는건지는 의문이긴 한데,
아예 unity gizmos(g,r,s handles)를 runtime에 object위에 띄우는 방법이 있다고 하네요.=
얘도 참고하면 어떨까 싶어요.

----- 아 유료에셋이네요 없던얘기로 ㅎㅎ ----------

**Comment by Aimee0122** [comment]
스티키노트 베이스 구현 이후에 추가적으로 더할 수 있는 기능들을 찾아보았습니다.
- 책상에 스티키 노트 붙었을 경우, 책상 가까이 다가가면 노트 허공에 표시
https://www.youtube.com/watch?v=eVre2i6gPF0
- UI적 요소 (타이핑 효과)
https://www.youtube.com/watch?v=OjcPuEVQT6s

**Comment by ahnjinmo** [comment]
## 베이스라인 (1/19~1/26)
- [X] 스티키노트 생성 및 삭제 기능 추가
- [X] 스티키노트 내용, 크기, 각도, 위치 수정 기능 추가

## 추가 디벨롭 가능사항 (1/26~)
- [ ] 스티키노트 내용 작성 중 캐릭터 움직임 막기
- [ ] 스티키노트 생성 시, 월드 내의 본인 플레이어 받아와서 일정 거리 앞에 생성되도록 만들기 (현재는 월드 영점에 생성되도록 구현함)

**Comment by ahnjinmo** [comment]
## 1차 디벨롭 (1/26~1/30)
- [X] 코드 리팩토링 (버튼 콜백, 이벤트 트리거 등을 모두 스크립트에서 바인딩하도록 수정)
- [X] Lock 기능 추가. Lock 버튼을 누르면 이동, 편집, 삭제 불가능
- [X] Remove 버튼을 일정 시간동안 누르고 있어야 스티키노트가 제거되는 기능 추가
- [X] Edit 모드에서 마우스 스크롤을 이용해 글씨의 크기를 조절하는 기능 추가

## 추가 디벨롭 가능사항 (1/26~)
- [ ] EditCanvas를 하나로 통일하기 (현재는 스티키노트 하나당 EditCanvas가 하나씩 같이 생성되어서 중복됨. 내용 편집 용 EditCanvas를 싱글톤 생성해서 이거 하나만 쓰는 방향으로 수정해야 할 듯함)
- [ ] 뒷면에서도 제대로 보이도록 하기, 뒷면에서도 클릭 가능하도록 하기
- [ ] 스티키노트 내용 작성 중 캐릭터 움직임 막기
- [ ] 스티키노트 생성 시, 월드 내의 본인 플레이어 받아와서 일정 거리 앞에 생성되도록 만들기 (현재는 월드 영점에 생성되도록 구현함)
