### ISSUE TITLE
photon계정 sharing 관련

### ISSUE THREAD

**Issue by AliceOfSNU** [XREAL-SNU/xTown#8]
photon app 이 한번 만들면 끝인게 아니라,
chat server 넣으려면 또 별도의 app을 만들어서
프로젝트 안에서는 그 app id로 server에 접속하는 것 같더라고요!

그래서 photon app추가를 자유롭게 할 수 있도록
photon 계정 공유하면 어떨까 싶습니다.

제가 생각하기엔 지금 photon은 이미 개인 메일로 되어 있어 어쩔 수 없지만 
앞으로는 공동으로 쓸 수 있는 gmail 파고 pw도 
기본 pw + otp 형식으로 기업에서 하는 것처럼 따라하는 것도 
괜찮을 것 같은데 어떠신가요?

**Comment by brainini** [comment]
이 issue를 지금에야 확인했네요 죄송합니다.
지금 저희 photon server도 개인 메일이 아니라 XTown 메일로 열어놓았습니다!!
밑에 아이디 및 비밀번호를 달아놓을테니 해당 아이디로 photon 홈페이지에 로그인해서 작업해주시면 될 것 같습니다.

ID : contact@xreal.info
PW : dprtmfldjf777 (한글로 엑스리얼777)

**Comment by AliceOfSNU** [comment]
확인했습니다 감사합니다
