### ISSUE TITLE
네트워크 - mainroom을 photon lobby에서 photon room으로 바꾸기

### ISSUE THREAD

**Issue by brainini** [XREAL-SNU/xTown#81]
## 목적
> 현재 lobby로 지정되 있는 mainroom을 room으로 만들어보기!!
## 작업 상세 내용
- [x] 현재 Photon 개념에서 lobby로 지정되 있는 mainroom을 room으로 만들어서 mainroom에서부터 player간 소통이 가능하게 하기

- [ ] PlayerTtl, EmptyRoomTtl을 설정해서 Portal타고 Back to Lobby 눌렀을 때 rejoin함수를 실행해서 새로 random한 방을 찾게하는 과정을 줄이자. 
- [ ] customproperty에 연결된 scene이름을 적어서 portal에서 filtering

**Comment by AliceOfSNU** [comment]
제가 생각하고 있던건, 야추 다이스같은 특별한 scene을 제외하고
아바타가 스폰되는 일반적인 room으로 이동하는 경우,
1-a) join random room 기본 + 플레이어 선택으로 현재 인원수 남아있는 룸 중 선택 또는 새 룸 생성
(플레이어가 룸을 직접 선택하는 기능은 친구와 같은 룸에 배정되고 싶을 때 등 필요가 있을 것으로 예상)
( 이 때, 현재 인원수 남아있는 룸들을 디스플레이 할 때는,
  i. 플레이어가 직접 생성한 room(이건 직접 생성한 룸이므로 '방제목'이 있을 것)을 생성 시간순으로 표시
  ii. 그 밑에 createOrJoinRandom으로 자동 생성된 room을 표시 (이건 room443, 447, 뭐 이런식으로 뜰 듯)
)

1-b) 현재는 portal 접속 후 currentRoomPanel을 보여주는데, 그거 없애고 로딩 스크린만 보여주고 바로 scene으로 들어가는게 어떨까 생각. 

1-c) 저번에도 말씀드리긴 했는데 플레이어 입장 후 해당 room이 roomlist에서 삭제되는 것에 대해서,
room이 여전히 list에 보였으면 좋겠다는생각. 8명 짜리 룸을 팠는데 3명 들어갔는데 그게 안 보여지면 리소스 낭비

3) 뭐 룸에서 다시 main room으로 나올때
 i. 이건 포털로 할지, exit 버튼을 통해 할지?
 ii. 사실 자신이 원래 있던 rooom으로 재배정 받는게 최선이라고 생각 (왜냐면 친구들과 같이 플레이 할 때, 같은 룸에 배정 받는게 best). 이거 가능할지

**Comment by AliceOfSNU** [comment]
![image](https://user-images.githubusercontent.com/86138312/150907651-451423e3-ee3d-405f-9fee-da0df7c025f1.png)
네트워크 작업은 OnJoinedRoom을 기다린 후 해야합니다.
예컨대 PhotonNetwork.Instantiate같은것은
OnJoinedRoom 이전에 할 경우, photon view에 대한 message dispatching에 문제가 발생할 수 있다고 합니다.

유의할 점은, Master client가 처음 룸을 만들고 들어갈 때에는, OnJoinedRoom 이후에 씬의 모든 object에 start가 호출되지만,

이미 있는 룸에 조인하는 클라이언트의 경우, 그 room이 Automatically sync scene이 활성화 되어 있다면, 모든 scene의 오브젝트가 로드 (Start) 되고 OnJoinedRoom이 호출됩니다.

따라서 Start에서 PhotonNetwork 를 쓰는 것이 위험할 수 있고, 꼭 OnJoinedROom을 기다려야 합니다.

**Comment by brainini** [comment]
- [ ] PlayerTtl, EmptyRoomTtl을 설정해서 Portal타고 Back to Lobby 눌렀을 때 rejoin함수를 실행해서 새로 random한 방을 찾게하는 과정을 줄이자. 
- [ ] customproperty에 연결된 scene이름을 적어서 portal에서 filtering
