### ISSUE TITLE
스티키노트 동기화

### ISSUE THREAD

**Issue by AliceOfSNU** [XREAL-SNU/xTown#84]
## 스티키 노트 동기화 할일
- [ ] ownership interface 구현
- [ ] rect transform 동기화
- [ ] text 동기화
- [ ] 플레이어가 scene을 나갈 때 object의 persistence 구현

## ownership interface

1) photon view를 붙인다. ownership을 인스펙터에서 **fixed -> request 또는 takeover**로 바꾼다.

2) script로 IPunOwnershipCallbacks를 구현하고, OnOwnershipRequest와 OnOwnershipTransfered등
인터페이스가 요구하는 메소드들을 채워넣는다.

3) IPunOwnershipCallbacks를 받기 위해서는, OnEnable 과 OnDisable에서 적절한 listener 등록해주어야 함.
void OnEnable()
{
    PhotonNetwork.AddCallbackTarget(this);
}

void OnDisable()
{
    PhotonNetwork.RemoveCallbackTarget(this);
}

4) 플레이어가 disconnect시에
![image](https://user-images.githubusercontent.com/86138312/151091264-70104a72-9876-42df-b407-28b6cb6aabc6.png)
이거 구현. PhotonNetwork.CurrentRoom.AutoCleanUp == false로 설정!!!
https://doc.photonengine.com/zh-cn/pun/current/pungameplay/ownershipandcontrol#takeover
기획따라 위의 페이지에서 Hard Disconnect시의 동작을 수정

**Comment by AliceOfSNU** [comment]
## Rect Transform 동기화
https://doc.photonengine.com/en-us/pun/current/gameplay/synchronization-and-state#making_the_most_of_synchronization__rpcs_and_properties

sticky note 가 transform대신 rect transform을 사용하는 UI element라서 photonTransformView는 사용 불가.

크게 두가지 방법을 후보로 생각하고 있음
1. OnPhotonSerializeView로 직접 rect transform의 position, rotation값들을 **실시간** 으로 동기화
2. RoomCustomProperties를 통한 동기화로, 한 플레이어가 스티키 노트를 에디트 하기 시작하면, 일단 다른플레이어들에게는 그 스티키노트를 안보이게 처리하고, 그 플레이어가 스티키노트 (다른 위치에 다른 각도로 갖다놓는다거나) edit마치면, 그 rect transform결과를 한번만 방 전체에 공지하는방법

### 두 방법의 비교
1) OnPhotonSerialize
+ 실시간으로 스티키노트가 커지고 작아지고 이동하는게 보이게 할 수 있다
+ edit하는동한 숨기는게 필요없어 로직이 간단하다
ㅡ SerializeView를 통한 streaming 방법은 비싼 연산이다. 실시간으로 스티키노트의 위치가 동기화 되는게 게임 내에서 그렇게 중요한 작업인지 기획 단에서 고민이 필요. 나중에 avatar animation등 다른 더 게임로직상 '중요한' 것들의 네트워킹 리소스를 잡아먹을 수 있음.
ㅡ  transformView가 제공하는 보간법이 없으면 다소 움직임이 stuttering 할 수 있음

2) RoomCustomProperties
+ 리소스를 최소한으로 사용함. 바뀐 최종 transform을 한번만 쏴주면 됨
ㅡ 실시간 동기화가 안됨.
ㅡ 플레이어가 스티키노트를 움직이는 동안 다른 플레이어한테 그 노트가 어떻게 보일지, 숨길지, 아님 원래 포지션에 그대로 보여도 부자연스럽진 않을지 등 기획상의 이슈를 고민해야함.

**Comment by AliceOfSNU** [comment]
### string동기화
RPC 쓰면 됨 이건 간단.
스티키노트에 PhotonView 컴포넌트 있는지 확인하고
[PhotonRPC]
PostNoteContent(string content) {
  text = content;
}
요거 스크립트에 달고, 
스트링 편집 완료시(confirm)
_view = GetComponent<PhotonView>();
if(_view.ownerActorNr != PhotonNetwork.LocalPlayer.ActorNumber) return;
_view.RPC("PostNoteContent", RPCTarget.All, content);
쏴주면 됨.

관련 도큐멘테이션
https://doc.photonengine.com/en-us/pun/current/gameplay/rpcsandraiseevent

**Comment by AliceOfSNU** [comment]
포톤 네트워킹 도큐멘테이션
https://lying-walrus-8c6.notion.site/Ownership-b9ec423070e74c44be9db1096127e372

**Comment by MondaySHB** [comment]
현재 해당 branch에서 test용 scene 및 포탈 새로 생성 완료했습니다.(이후 multi test에 활용하면 좋을 거 같습니다)
sticky note 내용 공유, scale, rotate, delete 모두 다른 사람들과 공유되도록 했습니다. 
1. edit 중에 중복 edit 해결해야 할 예정
2. PhotonTransformView 보다 RPC 위주로 사용하고자 OnDrag를 통한 구현에 중간 RPC 선언할 함수 만들어서 호출 구조refactoring 예정
3. StickyNote에 새로 추가 된 기능 반영할 예정
