### ISSUE TITLE
기본적인 chat 구현

### ISSUE THREAD

**Issue by AliceOfSNU** [XREAL-SNU/xTown#9]
baseline 챗 사용방법

1. play버튼 눌러 UI가 맞게 디스플레이되는지 확인 (화면 비율에 따라 UI가 표시 안되는 경우도 있음. 이럴땐 dont destroy on load> chatManager > canvas > chatpanel의 사이즈를 변경하면 보이긴 하나 근본적으로는 ui팀에서 문제를 확인해 줬으면 좋겠음.

2. 기본채널은 Default임. debug console에서 채널 이름 확인!

3. 메시지 보내려면 메시지 입력후 send button클릭 또는 enter

4. 새로운 채널에 subscribe하려면 \subscribe <채널이름> 입력
지금은 채널 이름 입력하면 그 채널이 새로 만들어짐.

5. 다른 채널로 이동하려면 \join <채널 이름!> 입력. 그러면 그 채널에 쌓인 메시지들이 쭉 보임(스크롤바 이용해서 위의 메시지들 확인 가능)

6. how to change id: chatManager inspector에서 UserID 원하는대로 변경

7. 현재 send to... 필드를 통한 private message는 지원하지 않으나 곧 추가예정

**Comment by AliceOfSNU** [comment]
코드 위치: assets > scripts > chat > photo chat manager.cs

**Comment by brainini** [comment]
필요한 수정사항 풀리퀘에 comment 달아놓았습니다.
